/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Natanael
 */
public class CaixaDecarrinhoProduto extends javax.swing.JPanel {

    /**
     * Creates new form caixaDecarrinhoProduto
     */
    public CaixaDecarrinhoProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2Carac = new javax.swing.JPanel();
        jLabel1Nome = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2Carac.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2Carac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        jPanel2Carac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1Nome.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2Carac.add(jLabel1Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        add(jPanel2Carac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 140));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1Nome;
    private javax.swing.JPanel jPanel2Carac;
    // End of variables declaration//GEN-END:variables
}
