/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Natanael
 */
public class CaixaDeCarrinhoInterna extends javax.swing.JPanel {

    /**
     * Creates new form CaixaDeCarrinhoInterna
     */
    public CaixaDeCarrinhoInterna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7NomeEmpresa = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9QuantiCarrinho = new javax.swing.JLabel();
        jLabel7CarrinhoTelaInicial = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7NomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7NomeEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7NomeEmpresa.setText("Inicio");
        jPanel4.add(jLabel7NomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 300, 10));

        jLabel9QuantiCarrinho.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9QuantiCarrinho.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9QuantiCarrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel9QuantiCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, 40));

        jLabel7CarrinhoTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/carrinho.png"))); // NOI18N
        jLabel7CarrinhoTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7CarrinhoTelaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7CarrinhoTelaInicialMouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7CarrinhoTelaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7CarrinhoTelaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7CarrinhoTelaInicialMouseClicked
        CaixaDeCarrinho caixaDeCarrinho = new CaixaDeCarrinho(new JanelaPrinci(), true);
        caixaDeCarrinho.setVisible(true);
    }//GEN-LAST:event_jLabel7CarrinhoTelaInicialMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7CarrinhoTelaInicial;
    private javax.swing.JLabel jLabel7NomeEmpresa;
    public static javax.swing.JLabel jLabel9QuantiCarrinho;
    private static javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
